# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 72c17a53c17b5efd6dfc64d1ef573dcd608617d2b2623f3a1edc25c52cb5e96bdc512d4754721f6d98d54273494cb60c15949c66f9a223c418df6b7c75b8a9fd

test:
  secret_key_base: 2640fc8382855ed6f8f2cbca8692f5cf4006d5b01455df6e229661f0e66b06ebdc35a8b494873b0e448d08678b204642ac35b3320eaa5f5845f9cab1f52a5ad0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
